---
- hosts: defaulthosts
  user: root
  # this playbook needs the "account_key" variable to be set which contains a "BOINC" account key
  # that is used to link the client with a user account
  tasks:

  - name: add virtualenv which is required for apt_repository
    pip: name=virtualenv state=present

  - name: add python_apt which is required for apt_repository
    pip: name=python_apt state=present

  - name: add Ethereum APT repository
    apt_repository: 
      repo: "ppa:ethereum/ethereum"
      update_cache: yes # this is actually the default
      state: present

  - name: install the Geth client 
    apt: pkg=ethereum state=present
