---
- hosts: defaulthosts
  user: root
  # this playbook needs the "account_key" variable to be set which contains a "BOINC" account key
  # that is used to link the client with a user account
  tasks:
  - fail: msg="the account_key variable to define the user to connect to is not defined"
    when: account_key is undefined

  - name: install the Boinc client for SETI@Home
    apt: pkg=boinc-client state=present

  - name: install overrides for configuration
    copy: src=setiathome_prefs.xml dest=/var/lib/boinc-client/global_prefs_override.xml owner=boinc group=boinc mode=0644

  - name: check SETI project connection status
    shell: boinccmd --get_project_status | grep setiathome.berkeley.edu | wc -l
    register: conn_status

  - name: connect Boinc client to my SETI project
    command: boinccmd --project_attach http://setiathome.berkeley.edu {{account_key}}
    when: conn_status == 0